-- 내꺼
WITH RECURSIVE rc AS (
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR + 1
FROM rc
WHERE HOUR < 23
) SELECT rc.HOUR, COUNT(outs.DATETIME) AS COUNT
FROM rc LEFT JOIN ANIMAL_OUTS outs ON
    rc.HOUR = DATE_FORMAT(outs.DATETIME, '%H')
GROUP BY rc.HOUR ORDER BY rc.HOUR;

-- 강사님꺼
WITH RECURSIVE number_sequence(HOUR) AS (
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 
    FROM number_sequence 
    WHERE HOUR < 23
)
SELECT HOUR, 0 AS COUNT FROM number_sequence
WHERE HOUR NOT IN (
    SELECT CAST(DATE_FORMAT(DATETIME, '%H') as signed) as HOUR FROM ANIMAL_OUTS
    )
UNION
SELECT CAST(DATE_FORMAT(DATETIME, '%H') AS signed) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS 
GROUP BY HOUR
ORDER BY HOUR;