-- 즐겨찾기가 가장 많은 식당 정보 출력하기
SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FAVORITES FROM(
	SELECT FOOD_TYPE, MAX(FAVORITES) as max_favorites
	FROM REST_INFO
	GROUP BY FOOD_TYPE
) t1 INNER JOIN REST_INFO 
ON t1.FOOD_TYPE = REST_INFO.FOOD_TYPE AND t1.max_favorites = REST_INFO.FAVORITES 
ORDER BY FOOD_TYPE DESC;

-- 없어진 기록 찾기
SELECT outs.ANIMAL_ID, outs.NAME
FROM ANIMAL_OUTS outs
LEFT JOIN ANIMAL_INS ins
on outs.ANIMAL_ID = ins.ANIMAL_ID
where ins.INTAKE_CONDITION is null;